# Generated by Django 5.0.3 on 2024-03-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_birth',
            field=models.DateField(verbose_name='date_birth'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateField(),
        ),
    ]
