# Generated by Django 5.0.3 on 2024-03-13 06:05

import django.db.models.deletion
import netflix.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_birth',
            field=models.DateField(validators=[netflix.validators.age_validator], verbose_name='date_birth'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=255, validators=[netflix.validators.starts_with_uppercase_validator, netflix.validators.contains_only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateField(validators=[netflix.validators.age_validator]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, validators=[netflix.validators.contains_only_letters_validator]),
        ),
    ]
